#!/usr/bin/env bash
# Headless-provision a freshly-flashed Raspberry Pi OS card for SkyView 2: enable SSH
# (key-only), join WiFi, create the user, set hostname/locale — by writing Raspberry
# Pi OS's `custom.toml` (processed on first boot) to the mounted boot partition. No
# screen/keyboard needed. (Shell counterpart to the Windows flash_skyview.ps1.)
#
# Usage (Linux/macOS, card mounted):
#   sudo BOOT_MNT=/mnt/sdboot \
#        WIFI_SSID="YourWiFi" WIFI_PSK="YourPassword" \
#        PUBKEY="$(cat ~/.ssh/id_ed25519.pub)" \
#        ./provision-sd.sh
set -euo pipefail

BOOT_MNT="${BOOT_MNT:?set BOOT_MNT to the mounted boot partition (e.g. /mnt/sdboot)}"
HOSTNAME_PI="${HOSTNAME_PI:-skyview}"        # matches install-on-pi.sh MDNS_HOST → skyview.local
USERNAME="${USERNAME:-pi}"
WIFI_SSID="${WIFI_SSID:?set WIFI_SSID}"
WIFI_PSK="${WIFI_PSK:?set WIFI_PSK}"
WIFI_COUNTRY="${WIFI_COUNTRY:-US}"
TIMEZONE="${TIMEZONE:-America/Los_Angeles}"
KEYMAP="${KEYMAP:-us}"
PUBKEY="${PUBKEY:?set PUBKEY to your SSH public key contents}"
# Console/sudo password for the user (SSH stays key-only). Random if unset.
USER_PASSWORD="${USER_PASSWORD:-$(openssl rand -base64 12)}"

[ -d "$BOOT_MNT" ] || { echo "ERROR: $BOOT_MNT is not mounted" >&2; exit 1; }
PW_HASH="$(openssl passwd -6 "$USER_PASSWORD")"

echo "==> Writing $BOOT_MNT/custom.toml"
cat > "$BOOT_MNT/custom.toml" <<EOF
# Generated by provision-sd.sh — Raspberry Pi OS first-boot customization.
config_version = 1

[system]
hostname = "$HOSTNAME_PI"

[user]
name = "$USERNAME"
password = "$PW_HASH"
password_encrypted = true

[ssh]
enabled = true
password_authentication = false
authorized_keys = [
  "$PUBKEY"
]

[wlan]
ssid = "$WIFI_SSID"
password = "$WIFI_PSK"
password_encrypted = false
hidden = false
country = "$WIFI_COUNTRY"

[locale]
keymap = "$KEYMAP"
timezone = "$TIMEZONE"
EOF

touch "$BOOT_MNT/ssh"   # belt-and-suspenders: enables sshd on every Pi OS release
sync

cat <<EOF

Provisioned:
  hostname : $HOSTNAME_PI   (try: ssh $USERNAME@$HOSTNAME_PI.local)
  user     : $USERNAME
  wifi     : $WIFI_SSID ($WIFI_COUNTRY)
  ssh      : key-only (password auth disabled)

  Console/sudo password (save this — needed for sudo on the Pi):
      $USER_PASSWORD

Eject the card, boot the Pi, wait ~60-90s for first-boot setup, then SSH in and run
install-on-pi.sh. If WiFi never associates, the Pi raises a 'SkyView-setup' hotspot
(see skyview-onboard) so you can still reach it.
EOF
